# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# There must be a more efficent way than this...
def fib(max_val=None):
    a = 1
    yield a
    b = 2
    while b < max_val if max_val else True:
        yield b
        a, b = b, a + b
        

if __name__ == '__main__':
    f = fib(4000000)
    result = sum(x for x in f if x % 2 == 0)
    print(result) # 4613732
